{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Unhandled Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\", type=\"general\"} | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "request_activeUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "userCount"
    }
   ]
  },
  {
   "title": "JWT Factory Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\", type=\"factory\"} | json"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\", type=\"database\"} | json"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\", type=\"http\"} | json"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "request_serviceLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "serviceEndpoints"
    },
    {
     "expr": "request_pizzaCreationLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "pizzaCreation"
    }
   ]
  },
  {
   "title": "Pizzas Sold/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(request_totalPizzaRevenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "revenue per minute"
    },
    {
     "expr": "rate(request_numPizzasSold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizzas sold per minute"
    },
    {
     "expr": "request_numCreationFailures{source=\"jwt-pizza-service\"}",
     "legendFormat": "pizza creation failures"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(request_authenticationSuccesses{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "authentication successes"
    },
    {
     "expr": "rate(request_authenticationFailures{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "authentication failures"
    }
   ]
  }
 ]
}